[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.34.0"
serde_json = "1.0.108"


ccxt = { git = "https://github.com/kizzx2/ccxt-rs-lib" }

